using System.Text;
using EnhancementHub.Application.Abstractions;

namespace EnhancementHub.Infrastructure.Services.Delivery;

public static class PlaywrightSpecGenerator
{
    public static string GenerateCombinedSpec(
        Guid enhancementRequestId,
        string testBaseUrl,
        IReadOnlyList<TestCaseExportItem> cases)
    {
        var shortId = enhancementRequestId.ToString("N")[..8];
        var sb = new StringBuilder();
        sb.AppendLine("import { test, expect } from '@playwright/test';");
        sb.AppendLine();
        sb.AppendLine($"// Generated by EnhancementHub for request {enhancementRequestId}");
        sb.AppendLine($"const baseUrl = process.env.EH_TEST_URL ?? '{EscapeJs(testBaseUrl)}';");
        sb.AppendLine();

        foreach (var testCase in cases)
        {
            var safeName = Slugify(testCase.Title);
            sb.AppendLine($"test('{EscapeJs(testCase.Title)}', async ({{ page }}) => {{");
            sb.AppendLine("  await page.goto(baseUrl);");
            sb.AppendLine("  await expect(page).toHaveURL(/./);");

            var steps = TestCasePlanParser.DeserializeSteps(testCase.StepsJson);
            foreach (var step in steps.OrderBy(s => s.Order))
            {
                sb.AppendLine($"  // Step {step.Order}: {EscapeJs(step.Action)}");
                if (step.Action.Contains("health", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine("  const health = await page.request.get(new URL('/health', baseUrl).toString());");
                    sb.AppendLine("  expect(health.ok()).toBeTruthy();");
                }
                else if (!string.IsNullOrWhiteSpace(step.ExpectedResult))
                {
                    sb.AppendLine($"  // Expected: {EscapeJs(step.ExpectedResult)}");
                }
            }

            sb.AppendLine("});");
            sb.AppendLine();
        }

        if (cases.Count == 0)
        {
            sb.AppendLine($"test('smoke-{shortId}', async ({{ page }}) => {{");
            sb.AppendLine("  await page.goto(baseUrl);");
            sb.AppendLine("  await expect(page).toHaveURL(/./);");
            sb.AppendLine("});");
        }

        return sb.ToString();
    }

    public static string SuggestRepositoryPath(Guid enhancementRequestId, string title)
    {
        var shortId = enhancementRequestId.ToString("N")[..8];
        var slug = Slugify(title);
        return $"tests/e2e/eh-{shortId}-{slug}.spec.ts";
    }

    private static string Slugify(string value)
    {
        var chars = value
            .ToLowerInvariant()
            .Select(c => char.IsLetterOrDigit(c) ? c : '-')
            .ToArray();
        var slug = new string(chars).Trim('-');
        while (slug.Contains("--", StringComparison.Ordinal))
        {
            slug = slug.Replace("--", "-", StringComparison.Ordinal);
        }

        return string.IsNullOrWhiteSpace(slug) ? "case" : slug[..Math.Min(slug.Length, 40)].Trim('-');
    }

    private static string EscapeJs(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("'", "\\'", StringComparison.Ordinal);
}
