apiVersion: v1
kind: Service
metadata:
  name: {{ include "enhancementhub.fullname" . }}-api
spec:
  selector:
    app: {{ include "enhancementhub.fullname" . }}-api
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8080
