apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enhancementhub.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: {{ include "enhancementhub.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "enhancementhub.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "enhancementhub.fullname" . }}-config
          env:
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret }}
                  key: connectionString
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
          readinessProbe:
            httpGet: { path: /health/ready, port: 8080 }
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
