apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enhancementhub.fullname" . }}-config
data:
  Database__Provider: {{ .Values.config.databaseProvider | quote }}
  BackgroundJobs__Provider: {{ .Values.config.backgroundJobsProvider | quote }}
  VectorSearch__Provider: {{ .Values.config.vectorSearchProvider | quote }}
  Observability__Enabled: {{ .Values.config.observabilityEnabled | quote }}
  Observability__OtlpEndpoint: {{ .Values.config.otlpEndpoint | quote }}
  Observability__EnablePrometheusMetrics: "true"
  DataProtection__StorageProvider: {{ .Values.dataProtection.storageProvider | quote }}
