// <auto-generated />
using System;
using EnhancementHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnhancementHub.Infrastructure.Migrations
{
    [DbContext(typeof(EnhancementHubDbContext))]
    [Migration("20260704105748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EnhancementAnalysisId");

                    b.ToTable("AffectedApplications", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComponentPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IndexedFileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.HasIndex("IndexedFileId");

                    b.ToTable("AffectedComponents", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("AffectedRepositories", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AiPromptConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("AiPromptConfigurations", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AiPromptRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructuredResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.HasIndex("EnhancementRequestId");

                    b.ToTable("AiPromptRuns", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AnalysisFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHumanApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.ToTable("AnalysisFindings", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApiChangeRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.ToTable("ApiChangeRecommendations", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDomain")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskSensitiveAreas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerTeamId");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApplicationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDomain")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseUsage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIntegrations")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalDependencies")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyComponents")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnershipMetadata")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskSensitiveAreas")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("ApplicationId", "RepositoryId");

                    b.ToTable("ApplicationProfiles", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiModelUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.HasIndex("EnhancementRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("ApprovalActions", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModelUsed")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RetrievedContextReferences")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.DatabaseChangeRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MigrationRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.ToTable("DatabaseChangeRecommendations", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbiguityNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalChecklist")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessGoal")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessRequirement")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureCategory")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApprovedSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsClarification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenQuestions")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskExplanation")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RollbackPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RolloutPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicalRequirements")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingPlan")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementRequestId", "Version");

                    b.ToTable("EnhancementAnalyses", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementRequestId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("EnhancementAttachments", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestedDueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportingNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TargetApplicationId");

                    b.HasIndex("TeamId");

                    b.ToTable("EnhancementRequests", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ExternalTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EnhancementRequestId");

                    b.HasIndex("Provider", "ExternalId");

                    b.ToTable("ExternalTickets", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.IndexedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EmbeddingVector")
                        .HasColumnType("BLOB");

                    b.Property<string>("ExtractedDependencies")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Project")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedApis")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedDatabaseObjects")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RepositoryId", "BranchId", "FilePath")
                        .IsUnique();

                    b.ToTable("IndexedFiles", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.IndexedSymbol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndexedFileId");

                    b.ToTable("IndexedSymbols", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitTokenSecretName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RepositoryBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommitHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "BranchName")
                        .IsUnique();

                    b.ToTable("RepositoryBranches", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RetrievedContextItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AiPromptRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IndexedFileId")
                        .HasColumnType("TEXT");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptRunId");

                    b.HasIndex("IndexedFileId");

                    b.ToTable("RetrievedContextItems", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RiskAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnhancementAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformanceConcerns")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityConcerns")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementAnalysisId");

                    b.ToTable("RiskAssessments", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedApplication", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Application", "Application")
                        .WithMany("AnalysisImpacts")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("AffectedApplications")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("EnhancementAnalysis");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedComponent", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("AffectedComponents")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.IndexedFile", "IndexedFile")
                        .WithMany("AnalysisImpacts")
                        .HasForeignKey("IndexedFileId");

                    b.Navigation("EnhancementAnalysis");

                    b.Navigation("IndexedFile");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AffectedRepository", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("AffectedRepositories")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.Repository", "Repository")
                        .WithMany("AnalysisImpacts")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AiPromptRun", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("AiPromptRuns")
                        .HasForeignKey("EnhancementAnalysisId");

                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("AiPromptRuns")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");

                    b.Navigation("EnhancementRequest");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AnalysisFinding", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("Findings")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApiChangeRecommendation", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("ApiChangeRecommendations")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Application", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Team", "OwnerTeam")
                        .WithMany("OwnedApplications")
                        .HasForeignKey("OwnerTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerTeam");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApplicationProfile", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Application", "Application")
                        .WithMany("Profiles")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.Repository", "Repository")
                        .WithMany("Profiles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ApprovalAction", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("EnhancementAnalysisId");

                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.User", "User")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");

                    b.Navigation("EnhancementRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Comment", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("Comments")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.DatabaseChangeRecommendation", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("DatabaseChangeRecommendations")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementAnalysis", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("Analyses")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementRequest");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementAttachment", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementRequest");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementRequest", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.User", "SubmittedByUser")
                        .WithMany("SubmittedRequests")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.Application", "TargetApplication")
                        .WithMany("TargetedRequests")
                        .HasForeignKey("TargetApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnhancementHub.Domain.Entities.Team", "Team")
                        .WithMany("EnhancementRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubmittedByUser");

                    b.Navigation("TargetApplication");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.ExternalTicket", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedExternalTickets")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementRequest", "EnhancementRequest")
                        .WithMany("ExternalTickets")
                        .HasForeignKey("EnhancementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("EnhancementRequest");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.IndexedFile", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.RepositoryBranch", "Branch")
                        .WithMany("IndexedFiles")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.Repository", "Repository")
                        .WithMany("IndexedFiles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.IndexedSymbol", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.IndexedFile", "IndexedFile")
                        .WithMany("Symbols")
                        .HasForeignKey("IndexedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexedFile");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Repository", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Application", "Application")
                        .WithMany("Repositories")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RepositoryBranch", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Repository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RetrievedContextItem", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.AiPromptRun", "AiPromptRun")
                        .WithMany("RetrievedContextItems")
                        .HasForeignKey("AiPromptRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.IndexedFile", "IndexedFile")
                        .WithMany("RetrievedContextItems")
                        .HasForeignKey("IndexedFileId");

                    b.Navigation("AiPromptRun");

                    b.Navigation("IndexedFile");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RiskAssessment", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.EnhancementAnalysis", "EnhancementAnalysis")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("EnhancementAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnhancementAnalysis");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("EnhancementHub.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnhancementHub.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.AiPromptRun", b =>
                {
                    b.Navigation("RetrievedContextItems");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Application", b =>
                {
                    b.Navigation("AnalysisImpacts");

                    b.Navigation("Profiles");

                    b.Navigation("Repositories");

                    b.Navigation("TargetedRequests");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementAnalysis", b =>
                {
                    b.Navigation("AffectedApplications");

                    b.Navigation("AffectedComponents");

                    b.Navigation("AffectedRepositories");

                    b.Navigation("AiPromptRuns");

                    b.Navigation("ApiChangeRecommendations");

                    b.Navigation("ApprovalActions");

                    b.Navigation("DatabaseChangeRecommendations");

                    b.Navigation("Findings");

                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.EnhancementRequest", b =>
                {
                    b.Navigation("AiPromptRuns");

                    b.Navigation("Analyses");

                    b.Navigation("ApprovalActions");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("ExternalTickets");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.IndexedFile", b =>
                {
                    b.Navigation("AnalysisImpacts");

                    b.Navigation("RetrievedContextItems");

                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Repository", b =>
                {
                    b.Navigation("AnalysisImpacts");

                    b.Navigation("Branches");

                    b.Navigation("IndexedFiles");

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.RepositoryBranch", b =>
                {
                    b.Navigation("IndexedFiles");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.Team", b =>
                {
                    b.Navigation("EnhancementRequests");

                    b.Navigation("Members");

                    b.Navigation("OwnedApplications");
                });

            modelBuilder.Entity("EnhancementHub.Domain.Entities.User", b =>
                {
                    b.Navigation("ApprovalActions");

                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("CreatedExternalTickets");

                    b.Navigation("SubmittedRequests");

                    b.Navigation("TeamMemberships");

                    b.Navigation("UploadedAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
